### ISSUE TITLE
GitHub Pages

### ISSUE THREAD

**Issue by thewilloftheshadow** [CarlyRaeJepsenStan/vanillanimate#1]
Good QOL improvement would be to have this repo on GitHub pages so that you can link to one/all of them without having to use Codepen or the TryIt editor

**Comment by aaronzshey** [comment]
Hmm.... how would this work?  Would the github pages directly consume the code in the files?

**Comment by thewilloftheshadow** [comment]
![image](https://user-images.githubusercontent.com/35580099/96333972-e0271900-1032-11eb-86a1-9480dc97089d.png)
Yep, the URLs would be https://CarlyRaeJepsenStan.github.io/vanillanimate/file.html

**Comment by aaronzshey** [comment]
Oh, cool!  I'll set this up soon.  Thanks for the tips and good luck with your discord bots :+1:

**Comment by aaronzshey** [comment]
Thanks for the tip, I got it working!  I'll edit the readme now.
